#dataset: "NYU" # "kitti", "kitti_360"
dataset: mix_dataset

n_relations: 4

enable_log: true
kitti_root: '/home/hez4sgh/data/shl/kitti'
kitti_preprocess_root: '/home/hez4sgh/data/shl/kitti/dataset/preprocess/monoscene'
kitti_logdir: '/home/hez4sgh/1_work_dir/SSCBench/method/MonoScene/logdir/kitti'

kitti_360_root: '/data/dataset2/SSCBench/sscbench-kitti'
kitti_360_preprocess_root: '/data/dataset2/SSCBench/sscbench-kitti/preprocess/unified'
kitti_360_logdir: '/home/hez4sgh/1_work_dir/SSCBench/method/MonoScene/logdir/kitti360'

nuscenes_root: '/data/dataset2/SSCBench/sscbench-nuscenes/'
nuscenes_preprocess_root: '/data/dataset2/SSCBench/sscbench-nuscenes/preprocess_uni/'
nuscenes_logdir: '/home/hez4sgh/1_work_dir/SSCBench/method/MonoScene/logdir/nuscenes'

waymo_root: '/data/dataset2/SSCBench/sscbench-waymo/Waymo/sscbench-waymo'
waymo_preprocess_root: '/data/dataset2/SSCBench/sscbench-waymo/Waymo/sscbench-waymo/preprocess/unified'
waymo_logdir: '/home/hez4sgh/1_work_dir/SSCBench/method/MonoScene/logdir/waymo'

NYU_root: '/path/to/NYU/depthbin'
NYU_preprocess_root: '/path/to/NYU/preprocess/folder'
logdir: '/path/to/NYU/logdir'

output_path:  '/home/hez4sgh/1_work_dir/SSCBench/method/MonoScene'

fp_loss: true 
frustum_size: 8 
batch_size: 8
n_gpus: 4
num_workers_per_gpu: 8
exp_prefix: "exp_1112_001_kw_right_cam"
run: 1
lr: 1e-4
weight_decay: 1e-4 

context_prior: true

relation_loss: true 
CE_ssc_loss: true
sem_scal_loss: true
geo_scal_loss: true

project_1_2: true
project_1_4: true
project_1_8: true
